version: '3'
services:
  directus:
    image: linefusion/directus:10.10.4-node20-alpine-runtime
    environment:
      # DIRECTUS_VERSION: '10.10.4'
      NODE_PACKAGES: |
        directus-extension-generate-types
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'true'

    ports:
      - '8055:8055'
